<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $this->command->info('Memulai seeding data Employee Eclectic Consulting...');

        $employees = [
            // 1. ADMIN
            [
                'eci' => 'ECI_ADMIN',
                'role_id' => 1,
                'basic' => [
                    'title' => 'Mr.',
                    'nick_name' => 'Admin',
                    'gender' => 'Laki-laki',
                    'religion' => 'Islam',
                    'first_name' => 'System',
                    'last_name' => 'Administrator',
                    'search_term_1' => 'SYSTEM',
                    'search_term_2' => 'ADMINISTRATOR',
                    'marital_status' => 'Belum Menikah',
                    'birth_date' => '1990-01-01',
                    'birth_place' => 'Yogyakarta',
                    'since_date' => '2020-01-01',
                    'created_by' => 'Seeder Script',
                    'created_on' => Carbon::now(),
                    'last_changed_by' => null,
                    'last_changed_on' => null,
                    'personnel_area' => 'PA-YOG',
                    'personnel_subarea' => 'PSA-SLEMAN',
                    'employee_group' => 'Administration',
                    'employee_subgroup' => 'System',
                    'position' => 'System Administrator',
                    'division' => 'IT & Security',
                    'department' => 'System Operations',
                    'direct_supervision' => null,
                    'manager' => null,
                    'authorization_group' => 'SYS-ADMIN',
                    'block' => false,
                    'deletion_flag' => false,
                ],
                'address' => [
                    'address_type' => 'Office',
                    'country' => 'Indonesia',
                    'region' => 'DI Yogyakarta',
                    'city' => 'Yogyakarta',
                    'district' => 'Sleman',
                    'rural_urban_village' => 'Catur Tunggal',
                    'street' => 'Jl. Kaliurang KM',
                    'house_number' => '5.6',
                    'postal_code' => '55281',
                    'language' => 'Indonesian',
                    'cell_phone_country' => 'ID',
                    'telephone_country' => 'ID',
                    'fax_country' => null,
                    'preferred_communication' => 'email',
                    'cell_phone' => '081290000000',
                    'telephone' => '0274-889900',
                    'telephone_extension' => null,
                    'fax' => null,
                    'fax_extension' => null,
                    'email_personal' => 'admin@eclectic.co.id',
                    'email_work' => 'admin@eclectic.co.id',
                    'website' => 'www.eclectic.co.id',
                    'valid_from' => '2020-01-01',
                    'valid_to' => null,
                    'is_primary' => true,
                    'is_verified' => true,
                ],
                'identification' => [
                    'identification_type' => 'KTP',
                    'identification_number' => '3404010101900001',
                    'responsible_institution' => 'Dukcapil Sleman',
                    'country' => 'Indonesia',
                    'region' => 'DI Yogyakarta',
                    'valid_from' => '2010-01-01',
                    'valid_to' => '2030-01-01',
                    'entry_date' => '2010-01-01',
                    'drive_link' => null,
                    'verify_link' => null,
                ],
                'family' => [
                    'name' => 'N/A',
                    'title' => null,
                    'relation' => 'Spouse',
                    'gender' => null,
                    'religion' => null,
                    'country' => null,
                    'birth_place' => null,
                    'birth_date' => null,
                    'occupation' => null,
                    'is_alive' => true,
                    'valid_from' => Carbon::now()->toDateString(),
                    'valid_to' => null,
                    'verify_link' => null,
                ],
                'education' => [
                    'education_type' => 'S1',
                    'institute_place' => 'Universitas Gadjah Mada',
                    'country' => 'Indonesia',
                    'degree' => 'Sarjana Komputer',
                    'duration_of_course' => '4 years',
                    'final_grade' => '3.80',
                    'branch_of_study' => 'Ilmu Komputer',
                    'start_year' => 2008,
                    'graduation_year' => 2012,
                    'unit' => 'Fakultas MIPA',
                    'valid_from' => '2012-09-01',
                    'valid_to' => null,
                    'attachment_name' => 'Ijazah S1',
                    'attachment_verify_link' => null,
                    'attachment_drive_link' => null,
                ],
                'qualification' => [
                    'qualification_type' => 'Certification',
                    'module' => 'Certified System Administrator',
                    'language' => 'English',
                    'qualification_level' => 'Expert',
                    'first_year' => '2018',
                    'certified' => true,
                    'dpm' => false,
                    'dsm' => true,
                    'valid_to' => '2028-04-20',
                    'valid_from' => '2018-04-20',
                    'drive_link' => null,
                    'verify_link' => null,
                ],
                'contract' => [
                    'contract_number' => 'CONT-2020-ADMIN',
                    'contract_name' => 'Permanent Admin Contract',
                    'contract_type' => 'PKWTT',
                    'contract_date' => '2020-01-01',
                    'position' => 'System Administrator',
                    'salary' => 15000000.00,
                    'start_date' => '2020-01-01',
                    'end_date' => null,
                    'is_active' => true,
                    'drive_link' => null,
                    'verify_link' => null,
                ],
                'bank' => [
                    'bank_name' => 'Bank BCA',
                    'bank_key' => 'BCA',
                    'account_number' => '5430012345678',
                    'account_holder' => 'System Administrator',
                    'drive_link' => null,
                    'valid_from' => '2020-01-01',
                    'valid_to' => null,
                    'verify_link' => null,
                ],
                'payment' => [
                    'amount' => 15000000.00,
                    'paid_at' => '2024-10-01',
                    'payment_method' => 'Transfer',
                    'reference_number' => 'PAY-2024-ADMIN-001',
                    'payment_status' => 'Completed',
                    'valid_to' => null,
                    'drive_link' => null,
                    'verify_link' => null,
                ],
            ],

            // 2. FERDINAND - Head of Project
            [
                'eci' => 'ECI_HOP',
                'role_id' => 4, // Head of Project
                'basic' => [
                    'title' => 'Mr.',
                    'nick_name' => 'Ferdinand',
                    'gender' => 'Laki-laki',
                    'religion' => 'Kristen',
                    'first_name' => 'Ferdinand',
                    'last_name' => 'Wijaya',
                    'search_term_1' => 'FERDINAND',
                    'search_term_2' => 'WIJAYA',
                    'marital_status' => 'Menikah',
                    'birth_date' => '1985-05-15',
                    'birth_place' => 'Yogyakarta',
                    'since_date' => '2018-01-01',
                    'created_by' => 'HR Admin',
                    'created_on' => Carbon::now(),
                    'last_changed_by' => null,
                    'last_changed_on' => null,
                    'personnel_area' => 'PA-YOG',
                    'personnel_subarea' => 'PSA-SLEMAN',
                    'employee_group' => 'Management',
                    'employee_subgroup' => 'Head',
                    'position' => 'Head of Project',
                    'division' => 'Consulting Services',
                    'department' => 'Project Delivery',
                    'direct_supervision' => null,
                    'manager' => 'Director',
                    'authorization_group' => 'HEAD-PROJECT',
                    'block' => false,
                    'deletion_flag' => false,
                ],
                'address' => [
                    'address_type' => 'Home',
                    'country' => 'Indonesia',
                    'region' => 'DI Yogyakarta',
                    'city' => 'Yogyakarta',
                    'district' => 'Sleman',
                    'rural_urban_village' => 'Condong Catur',
                    'street' => 'Jl. Kaliurang',
                    'house_number' => '100',
                    'postal_code' => '55281',
                    'language' => 'Indonesian',
                    'cell_phone_country' => 'ID',
                    'telephone_country' => 'ID',
                    'fax_country' => null,
                    'preferred_communication' => 'email',
                    'cell_phone' => '081234567100',
                    'telephone' => '0274-889100',
                    'telephone_extension' => null,
                    'fax' => null,
                    'fax_extension' => null,
                    'email_personal' => 'ferdinand.wijaya@gmail.com',
                    'email_work' => 'ferdinand@eclectic.co.id',
                    'website' => null,
                    'valid_from' => '2018-01-01',
                    'valid_to' => null,
                    'is_primary' => true,
                    'is_verified' => true,
                ],
                'identification' => [
                    'identification_type' => 'KTP',
                    'identification_number' => '3404011505850001',
                    'responsible_institution' => 'Dukcapil Sleman',
                    'country' => 'Indonesia',
                    'region' => 'DI Yogyakarta',
                    'valid_from' => '2003-05-15',
                    'valid_to' => '2043-05-15',
                    'entry_date' => '2003-05-15',
                    'drive_link' => null,
                    'verify_link' => null,
                ],
                'family' => [
                    'name' => 'Maria Wijaya',
                    'title' => 'Mrs.',
                    'relation' => 'Spouse',
                    'gender' => 'Perempuan',
                    'religion' => 'Kristen',
                    'country' => 'Indonesia',
                    'birth_place' => 'Yogyakarta',
                    'birth_date' => '1987-08-20',
                    'occupation' => 'Accountant',
                    'is_alive' => true,
                    'valid_from' => '2012-06-15',
                    'valid_to' => null,
                    'verify_link' => null,
                ],
                'education' => [
                    'education_type' => 'S2',
                    'institute_place' => 'Universitas Gadjah Mada',
                    'country' => 'Indonesia',
                    'degree' => 'Magister Manajemen',
                    'duration_of_course' => '2 years',
                    'final_grade' => '3.85',
                    'branch_of_study' => 'Manajemen Proyek',
                    'start_year' => 2010,
                    'graduation_year' => 2012,
                    'unit' => 'Fakultas Ekonomika dan Bisnis',
                    'valid_from' => '2012-09-01',
                    'valid_to' => null,
                    'attachment_name' => 'Ijazah S2',
                    'attachment_verify_link' => null,
                    'attachment_drive_link' => null,
                ],
                'qualification' => [
                    'qualification_type' => 'Certification',
                    'module' => 'Project Management Professional (PMP)',
                    'language' => 'English',
                    'qualification_level' => 'Expert',
                    'first_year' => '2015',
                    'certified' => true,
                    'dpm' => true,
                    'dsm' => true,
                    'valid_to' => '2030-12-31',
                    'valid_from' => '2015-06-01',
                    'drive_link' => null,
                    'verify_link' => null,
                ],
                'contract' => [
                    'contract_number' => 'CONT-2018-HOP',
                    'contract_name' => 'Permanent Head of Project',
                    'contract_type' => 'PKWTT',
                    'contract_date' => '2017-12-20',
                    'position' => 'Head of Project',
                    'salary' => 25000000.00,
                    'start_date' => '2018-01-01',
                    'end_date' => null,
                    'is_active' => true,
                    'drive_link' => null,
                    'verify_link' => null,
                ],
                'bank' => [
                    'bank_name' => 'Bank BCA',
                    'bank_key' => 'BCA',
                    'account_number' => '5430099990001',
                    'account_holder' => 'Ferdinand Wijaya',
                    'drive_link' => null,
                    'valid_from' => '2018-01-01',
                    'valid_to' => null,
                    'verify_link' => null,
                ],
                'payment' => [
                    'amount' => 25000000.00,
                    'paid_at' => '2024-10-01',
                    'payment_method' => 'Transfer',
                    'reference_number' => 'PAY-2024-HOP-001',
                    'payment_status' => 'Completed',
                    'valid_to' => null,
                    'drive_link' => null,
                    'verify_link' => null,
                ],
            ],

            // 3. ANTONIUS - Head of Support
            [
                'eci' => 'ECI_HOS',
                'role_id' => 5, // Head of Support
                'basic' => [
                    'title' => 'Mr.',
                    'nick_name' => 'Antonius',
                    'gender' => 'Laki-laki',
                    'religion' => 'Katolik',
                    'first_name' => 'Antonius',
                    'last_name' => 'Kusuma',
                    'search_term_1' => 'ANTONIUS',
                    'search_term_2' => 'KUSUMA',
                    'marital_status' => 'Menikah',
                    'birth_date' => '1983-10-25',
                    'birth_place' => 'Semarang',
                    'since_date' => '2017-06-01',
                    'created_by' => 'HR Admin',
                    'created_on' => Carbon::now(),
                    'last_changed_by' => null,
                    'last_changed_on' => null,
                    'personnel_area' => 'PA-YOG',
                    'personnel_subarea' => 'PSA-SLEMAN',
                    'employee_group' => 'Management',
                    'employee_subgroup' => 'Head',
                    'position' => 'Head of Support',
                    'division' => 'Consulting Services',
                    'department' => 'Support',
                    'direct_supervision' => null,
                    'manager' => 'Director',
                    'authorization_group' => 'HEAD-SUPPORT',
                    'block' => false,
                    'deletion_flag' => false,
                ],
                'address' => [
                    'address_type' => 'Home',
                    'country' => 'Indonesia',
                    'region' => 'DI Yogyakarta',
                    'city' => 'Yogyakarta',
                    'district' => 'Sleman',
                    'rural_urban_village' => 'Depok',
                    'street' => 'Jl. Affandi',
                    'house_number' => '55',
                    'postal_code' => '55281',
                    'language' => 'Indonesian',
                    'cell_phone_country' => 'ID',
                    'telephone_country' => 'ID',
                    'fax_country' => null,
                    'preferred_communication' => 'email',
                    'cell_phone' => '081234567200',
                    'telephone' => '0274-889200',
                    'telephone_extension' => null,
                    'fax' => null,
                    'fax_extension' => null,
                    'email_personal' => 'antonius.kusuma@gmail.com',
                    'email_work' => 'antonius@eclectic.co.id',
                    'website' => null,
                    'valid_from' => '2017-06-01',
                    'valid_to' => null,
                    'is_primary' => true,
                    'is_verified' => true,
                ],
                'identification' => [
                    'identification_type' => 'KTP',
                    'identification_number' => '3374052510830001',
                    'responsible_institution' => 'Dukcapil Semarang',
                    'country' => 'Indonesia',
                    'region' => 'Jawa Tengah',
                    'valid_from' => '2001-10-25',
                    'valid_to' => '2041-10-25',
                    'entry_date' => '2001-10-25',
                    'drive_link' => null,
                    'verify_link' => null,
                ],
                'family' => [
                    'name' => 'Clara Kusuma',
                    'title' => 'Mrs.',
                    'relation' => 'Spouse',
                    'gender' => 'Perempuan',
                    'religion' => 'Katolik',
                    'country' => 'Indonesia',
                    'birth_place' => 'Semarang',
                    'birth_date' => '1985-03-10',
                    'occupation' => 'Teacher',
                    'is_alive' => true,
                    'valid_from' => '2010-08-20',
                    'valid_to' => null,
                    'verify_link' => null,
                ],
                'education' => [
                    'education_type' => 'S1',
                    'institute_place' => 'Universitas Diponegoro',
                    'country' => 'Indonesia',
                    'degree' => 'Sarjana Teknik',
                    'duration_of_course' => '4 years',
                    'final_grade' => '3.75',
                    'branch_of_study' => 'Teknik Informatika',
                    'start_year' => 2001,
                    'graduation_year' => 2005,
                    'unit' => 'Fakultas Teknik',
                    'valid_from' => '2005-09-01',
                    'valid_to' => null,
                    'attachment_name' => 'Ijazah S1',
                    'attachment_verify_link' => null,
                    'attachment_drive_link' => null,
                ],
                'qualification' => [
                    'qualification_type' => 'Certification',
                    'module' => 'ITIL Foundation',
                    'language' => 'English',
                    'qualification_level' => 'Expert',
                    'first_year' => '2012',
                    'certified' => true,
                    'dpm' => true,
                    'dsm' => true,
                    'valid_to' => '2030-12-31',
                    'valid_from' => '2012-03-01',
                    'drive_link' => null,
                    'verify_link' => null,
                ],
                'contract' => [
                    'contract_number' => 'CONT-2017-HOS',
                    'contract_name' => 'Permanent Head of Support',
                    'contract_type' => 'PKWTT',
                    'contract_date' => '2017-05-20',
                    'position' => 'Head of Support',
                    'salary' => 23000000.00,
                    'start_date' => '2017-06-01',
                    'end_date' => null,
                    'is_active' => true,
                    'drive_link' => null,
                    'verify_link' => null,
                ],
                'bank' => [
                    'bank_name' => 'Bank Mandiri',
                    'bank_key' => 'BMRI',
                    'account_number' => '1370099990002',
                    'account_holder' => 'Antonius Kusuma',
                    'drive_link' => null,
                    'valid_from' => '2017-06-01',
                    'valid_to' => null,
                    'verify_link' => null,
                ],
                'payment' => [
                    'amount' => 23000000.00,
                    'paid_at' => '2024-10-01',
                    'payment_method' => 'Transfer',
                    'reference_number' => 'PAY-2024-HOS-001',
                    'payment_status' => 'Completed',
                    'valid_to' => null,
                    'drive_link' => null,
                    'verify_link' => null,
                ],
            ],

            // 4. HELPDESK STAFF
            [
                'eci' => 'ECI_HELPDESK',
                'role_id' => 6, // Helpdesk
                'basic' => [
                    'title' => 'Mr.',
                    'nick_name' => 'Helpdesk',
                    'gender' => 'Laki-laki',
                    'religion' => 'Islam',
                    'first_name' => 'Helpdesk',
                    'last_name' => 'Support',
                    'search_term_1' => 'HELPDESK',
                    'search_term_2' => 'SUPPORT',
                    'marital_status' => 'Belum Menikah',
                    'birth_date' => '1995-01-01',
                    'birth_place' => 'Yogyakarta',
                    'since_date' => Carbon::now()->toDateString(),
                    'created_by' => 'HR Admin',
                    'created_on' => Carbon::now(),
                    'last_changed_by' => null,
                    'last_changed_on' => null,
                    'personnel_area' => 'PA-YOG',
                    'personnel_subarea' => 'PSA-SLEMAN',
                    'employee_group' => 'Support',
                    'employee_subgroup' => 'Helpdesk',
                    'position' => 'Helpdesk Staff',
                    'division' => 'Support',
                    'department' => 'Customer Support',
                    'direct_supervision' => null,
                    'manager' => 'Head of Support',
                    'authorization_group' => 'HELPDESK',
                    'block' => false,
                    'deletion_flag' => false,
                ],
                'address' => [
                    'address_type' => 'Office',
                    'country' => 'Indonesia',
                    'region' => 'DI Yogyakarta',
                    'city' => 'Yogyakarta',
                    'district' => 'Sleman',
                    'rural_urban_village' => 'Catur Tunggal',
                    'street' => 'Jl. Kaliurang KM',
                    'house_number' => '5.6',
                    'postal_code' => '55281',
                    'language' => 'Indonesian',
                    'cell_phone_country' => 'ID',
                    'telephone_country' => 'ID',
                    'fax_country' => null,
                    'preferred_communication' => 'email',
                    'cell_phone' => '081290000006',
                    'telephone' => '0274-889906',
                    'telephone_extension' => null,
                    'fax' => null,
                    'fax_extension' => null,
                    'email_personal' => 'helpdesk@gmail.com',
                    'email_work' => 'helpdesk@eclectic.co.id',
                    'website' => null,
                    'valid_from' => Carbon::now()->toDateString(),
                    'valid_to' => null,
                    'is_primary' => true,
                    'is_verified' => true,
                ],
                'identification' => [
                    'identification_type' => 'KTP',
                    'identification_number' => '3404010101950006',
                    'responsible_institution' => 'Dukcapil Sleman',
                    'country' => 'Indonesia',
                    'region' => 'DI Yogyakarta',
                    'valid_from' => '2013-01-01',
                    'valid_to' => '2033-01-01',
                    'entry_date' => '2013-01-01',
                    'drive_link' => null,
                    'verify_link' => null,
                ],
                'family' => [
                    'name' => 'N/A',
                    'title' => null,
                    'relation' => 'Spouse',
                    'gender' => null,
                    'religion' => null,
                    'country' => null,
                    'birth_place' => null,
                    'birth_date' => null,
                    'occupation' => null,
                    'is_alive' => true,
                    'valid_from' => Carbon::now()->toDateString(),
                    'valid_to' => null,
                    'verify_link' => null,
                ],
                'education' => [
                    'education_type' => 'S1',
                    'institute_place' => 'Universitas Atma Jaya Yogyakarta',
                    'country' => 'Indonesia',
                    'degree' => 'Sarjana Komputer',
                    'duration_of_course' => '4 years',
                    'final_grade' => '3.50',
                    'branch_of_study' => 'Sistem Informasi',
                    'start_year' => 2013,
                    'graduation_year' => 2017,
                    'unit' => 'Fakultas Teknologi Industri',
                    'valid_from' => '2017-09-01',
                    'valid_to' => null,
                    'attachment_name' => 'Ijazah S1',
                    'attachment_verify_link' => null,
                    'attachment_drive_link' => null,
                ],
                'qualification' => [
                    'qualification_type' => 'Certification',
                    'module' => 'IT Helpdesk Support',
                    'language' => 'Indonesian',
                    'qualification_level' => 'Intermediate',
                    'first_year' => '2020',
                    'certified' => true,
                    'dpm' => false,
                    'dsm' => true, // Enable DSM for support access
                    'valid_to' => '2030-12-31',
                    'valid_from' => '2020-01-01',
                    'drive_link' => null,
                    'verify_link' => null,
                ],
                'contract' => [
                    'contract_number' => 'CONT-2020-HELPDESK',
                    'contract_name' => 'Permanent Helpdesk Staff',
                    'contract_type' => 'PKWTT',
                    'contract_date' => '2020-01-01',
                    'position' => 'Helpdesk Staff',
                    'salary' => 8000000.00,
                    'start_date' => '2020-01-01',
                    'end_date' => null,
                    'is_active' => true,
                    'drive_link' => null,
                    'verify_link' => null,
                ],
                'bank' => [
                    'bank_name' => 'Bank BCA',
                    'bank_key' => 'BCA',
                    'account_number' => '5430012345006',
                    'account_holder' => 'Helpdesk Support',
                    'drive_link' => null,
                    'valid_from' => '2020-01-01',
                    'valid_to' => null,
                    'verify_link' => null,
                ],
                'payment' => [
                    'amount' => 8000000.00,
                    'paid_at' => '2024-10-01',
                    'payment_method' => 'Transfer',
                    'reference_number' => 'PAY-2024-HELPDESK-001',
                    'payment_status' => 'Completed',
                    'valid_to' => null,
                    'drive_link' => null,
                    'verify_link' => null,
                ],
            ],

            // 5. RPMO - Arbin Hanley Saputra
            [
                'eci' => 'ECI_RPMO',
                'role_id' => 7, // RPMO
                'basic' => [
                    'title' => 'Mr.',
                    'nick_name' => 'Arbin',
                    'gender' => 'Laki-laki',
                    'religion' => 'Islam',
                    'first_name' => 'Arbin Hanley',
                    'last_name' => 'Saputra',
                    'search_term_1' => 'ARBIN',
                    'search_term_2' => 'SAPUTRA',
                    'marital_status' => 'Belum Menikah',
                    'birth_date' => '1993-06-15',
                    'birth_place' => 'Yogyakarta',
                    'since_date' => Carbon::now()->toDateString(),
                    'created_by' => 'HR Admin',
                    'created_on' => Carbon::now(),
                    'last_changed_by' => null,
                    'last_changed_on' => null,
                    'personnel_area' => 'PA-YOG',
                    'personnel_subarea' => 'PSA-SLEMAN',
                    'employee_group' => 'Management',
                    'employee_subgroup' => 'RPMO',
                    'position' => 'Resource & Project Management Officer',
                    'division' => 'Operations',
                    'department' => 'Project Management Office',
                    'direct_supervision' => null,
                    'manager' => 'Director',
                    'authorization_group' => 'RPMO',
                    'block' => false,
                    'deletion_flag' => false,
                ],
                'address' => [
                    'address_type' => 'Office',
                    'country' => 'Indonesia',
                    'region' => 'DI Yogyakarta',
                    'city' => 'Yogyakarta',
                    'district' => 'Sleman',
                    'rural_urban_village' => 'Catur Tunggal',
                    'street' => 'Jl. Kaliurang KM',
                    'house_number' => '5.6',
                    'postal_code' => '55281',
                    'language' => 'Indonesian',
                    'cell_phone_country' => 'ID',
                    'telephone_country' => 'ID',
                    'fax_country' => null,
                    'preferred_communication' => 'email',
                    'cell_phone' => '081290000007',
                    'telephone' => '0274-889907',
                    'telephone_extension' => null,
                    'fax' => null,
                    'fax_extension' => null,
                    'email_personal' => 'arbin.saputra@gmail.com',
                    'email_work' => 'arbin@eclectic.co.id',
                    'website' => null,
                    'valid_from' => Carbon::now()->toDateString(),
                    'valid_to' => null,
                    'is_primary' => true,
                    'is_verified' => true,
                ],
                'identification' => [
                    'identification_type' => 'KTP',
                    'identification_number' => '3404011506930007',
                    'responsible_institution' => 'Dukcapil Sleman',
                    'country' => 'Indonesia',
                    'region' => 'DI Yogyakarta',
                    'valid_from' => '2011-06-15',
                    'valid_to' => '2031-06-15',
                    'entry_date' => '2011-06-15',
                    'drive_link' => null,
                    'verify_link' => null,
                ],
                'family' => [
                    'name' => 'N/A',
                    'title' => null,
                    'relation' => 'Spouse',
                    'gender' => null,
                    'religion' => null,
                    'country' => null,
                    'birth_place' => null,
                    'birth_date' => null,
                    'occupation' => null,
                    'is_alive' => true,
                    'valid_from' => Carbon::now()->toDateString(),
                    'valid_to' => null,
                    'verify_link' => null,
                ],
                'education' => [
                    'education_type' => 'S1',
                    'institute_place' => 'Universitas Gadjah Mada',
                    'country' => 'Indonesia',
                    'degree' => 'Sarjana Manajemen',
                    'duration_of_course' => '4 years',
                    'final_grade' => '3.70',
                    'branch_of_study' => 'Manajemen',
                    'start_year' => 2011,
                    'graduation_year' => 2015,
                    'unit' => 'Fakultas Ekonomika dan Bisnis',
                    'valid_from' => '2015-09-01',
                    'valid_to' => null,
                    'attachment_name' => 'Ijazah S1',
                    'attachment_verify_link' => null,
                    'attachment_drive_link' => null,
                ],
                'qualification' => [
                    'qualification_type' => 'Certification',
                    'module' => 'Project Management Professional',
                    'language' => 'English',
                    'qualification_level' => 'Professional',
                    'first_year' => '2018',
                    'certified' => true,
                    'dpm' => true,
                    'dsm' => true,
                    'valid_to' => '2030-12-31',
                    'valid_from' => '2018-01-01',
                    'drive_link' => null,
                    'verify_link' => null,
                ],
                'contract' => [
                    'contract_number' => 'CONT-2020-RPMO',
                    'contract_name' => 'Permanent RPMO Staff',
                    'contract_type' => 'PKWTT',
                    'contract_date' => '2020-01-01',
                    'position' => 'Resource & Project Management Officer',
                    'salary' => 12000000.00,
                    'start_date' => '2020-01-01',
                    'end_date' => null,
                    'is_active' => true,
                    'drive_link' => null,
                    'verify_link' => null,
                ],
                'bank' => [
                    'bank_name' => 'Bank BCA',
                    'bank_key' => 'BCA',
                    'account_number' => '5430012345007',
                    'account_holder' => 'Arbin Hanley Saputra',
                    'drive_link' => null,
                    'valid_from' => '2020-01-01',
                    'valid_to' => null,
                    'verify_link' => null,
                ],
                'payment' => [
                    'amount' => 12000000.00,
                    'paid_at' => '2024-10-01',
                    'payment_method' => 'Transfer',
                    'reference_number' => 'PAY-2024-RPMO-001',
                    'payment_status' => 'Completed',
                    'valid_to' => null,
                    'drive_link' => null,
                    'verify_link' => null,
                ],
            ],

            // 6. ARI
            [
                'eci' => 'ECI001',
                'basic' => [
                    'title' => 'Mr.',
                    'nick_name' => 'Ari',
                    'gender' => 'Laki-laki',
                    'religion' => 'Islam',
                    'first_name' => 'Ari',
                    'last_name' => 'Wibowo',
                    'search_term_1' => 'ARI',
                    'search_term_2' => 'WIBOWO',
                    'marital_status' => 'Menikah',
                    'birth_date' => '1988-03-15',
                    'birth_place' => 'Yogyakarta',
                    'since_date' => '2020-02-01',
                    'created_by' => 'HR Admin',
                    'created_on' => Carbon::now(),
                    'personnel_area' => 'PA-YOG',
                    'personnel_subarea' => 'PSA-SLEMAN',
                    'employee_group' => 'Professional',
                    'employee_subgroup' => 'Consultant',
                    'position' => 'Senior Consultant',
                    'division' => 'Consulting Services',
                    'department' => 'Business Consulting',
                    'direct_supervision' => null,
                    'manager' => 'Director',
                    'authorization_group' => 'CONSULTANT',
                    'block' => false,
                    'deletion_flag' => false,
                ],
                'address' => [
                    'address_type' => 'Home',
                    'country' => 'Indonesia',
                    'region' => 'DI Yogyakarta',
                    'city' => 'Yogyakarta',
                    'district' => 'Sleman',
                    'rural_urban_village' => 'Depok',
                    'street' => 'Jl. Affandi',
                    'house_number' => '12',
                    'postal_code' => '55281',
                    'language' => 'Indonesian',
                    'cell_phone_country' => 'ID',
                    'telephone_country' => 'ID',
                    'preferred_communication' => 'email',
                    'cell_phone' => '081234567001',
                    'telephone' => '0274-512345',
                    'email_personal' => 'ari.wibowo@gmail.com',
                    'email_work' => 'ari@eclectic.co.id',
                    'valid_from' => '2020-02-01',
                    'is_primary' => true,
                    'is_verified' => true,
                ],
                'identification' => [
                    'identification_type' => 'KTP',
                    'identification_number' => '3404011503880001',
                    'responsible_institution' => 'Dukcapil Sleman',
                    'country' => 'Indonesia',
                    'region' => 'DI Yogyakarta',
                    'valid_from' => '2006-03-15',
                    'valid_to' => '2026-03-15',
                    'entry_date' => '2006-03-15',
                ],
                'family' => [
                    'name' => 'Sari Wulandari',
                    'title' => 'Mrs.',
                    'relation' => 'Spouse',
                    'gender' => 'Perempuan',
                    'religion' => 'Islam',
                    'country' => 'Indonesia',
                    'birth_place' => 'Yogyakarta',
                    'birth_date' => '1990-05-20',
                    'occupation' => 'Teacher',
                    'is_alive' => true,
                    'valid_from' => '2012-06-15',
                ],
                'education' => [
                    'education_type' => 'S1',
                    'institute_place' => 'Universitas Gadjah Mada',
                    'country' => 'Indonesia',
                    'degree' => 'Sarjana Ekonomi',
                    'duration_of_course' => '4 years',
                    'final_grade' => '3.65',
                    'branch_of_study' => 'Manajemen',
                    'start_year' => 2006,
                    'graduation_year' => 2010,
                    'unit' => 'Fakultas Ekonomika dan Bisnis',
                    'valid_from' => '2010-09-01',
                    'attachment_name' => 'Ijazah S1',
                ],
                'qualification' => [
                    'qualification_type' => 'Certification',
                    'module' => 'Project Management Professional',
                    'language' => 'English',
                    'qualification_level' => 'Professional',
                    'first_year' => '2019',
                    'certified' => true,
                    'dpm' => true,
                    'dsm' => false,
                    'valid_to' => '2026-12-31',
                    'valid_from' => '2019-01-15',
                ],
                'contract' => [
                    'contract_number' => 'CONT-2020-001',
                    'contract_name' => 'Permanent Employment',
                    'contract_type' => 'PKWTT',
                    'contract_date' => '2020-01-25',
                    'position' => 'Senior Consultant',
                    'salary' => 18000000.00,
                    'start_date' => '2020-02-01',
                    'is_active' => true,
                ],
                'bank' => [
                    'bank_name' => 'Bank Mandiri',
                    'bank_key' => 'BMRI',
                    'account_number' => '1370001234567',
                    'account_holder' => 'Ari Wibowo',
                    'valid_from' => '2020-02-01',
                ],
                'payment' => [
                    'amount' => 18000000.00,
                    'paid_at' => '2024-10-01',
                    'payment_method' => 'Transfer',
                    'reference_number' => 'PAY-2024-10-001',
                    'payment_status' => 'Completed',
                ],
            ],

            // 3. AROGYA (EXT)
            [
                'eci' => 'ECI002',
                'basic' => [
                    'title' => 'Mr.',
                    'nick_name' => 'Arogya',
                    'gender' => 'Laki-laki',
                    'religion' => 'Hindu',
                    'first_name' => 'Arogya',
                    'last_name' => 'Prasetya',
                    'search_term_1' => 'AROGYA',
                    'search_term_2' => 'PRASETYA',
                    'marital_status' => 'Belum Menikah',
                    'birth_date' => '1995-07-22',
                    'birth_place' => 'Denpasar',
                    'since_date' => '2022-03-15',
                    'created_by' => 'HR Admin',
                    'created_on' => Carbon::now(),
                    'personnel_area' => 'PA-YOG',
                    'personnel_subarea' => 'PSA-SLEMAN',
                    'employee_group' => 'Professional',
                    'employee_subgroup' => 'Consultant',
                    'position' => 'Junior Consultant',
                    'division' => 'Consulting Services',
                    'department' => 'Project Support',
                    'direct_supervision' => 'ECI001',
                    'manager' => 'Ari Wibowo',
                    'authorization_group' => 'EXTERNAL',
                    'block' => false,
                    'deletion_flag' => false,
                ],
                'address' => [
                    'address_type' => 'Home',
                    'country' => 'Indonesia',
                    'region' => 'DI Yogyakarta',
                    'city' => 'Yogyakarta',
                    'district' => 'Sleman',
                    'rural_urban_village' => 'Condong Catur',
                    'street' => 'Jl. Seturan',
                    'house_number' => '45',
                    'postal_code' => '55281',
                    'language' => 'Indonesian',
                    'cell_phone_country' => 'ID',
                    'telephone_country' => 'ID',
                    'preferred_communication' => 'phone',
                    'cell_phone' => '081234567002',
                    'telephone' => '0274-512346',
                    'email_personal' => 'arogya.prasetya@gmail.com',
                    'email_work' => 'arogya.ext@eclectic.co.id',
                    'valid_from' => '2022-03-15',
                    'is_primary' => true,
                    'is_verified' => true,
                ],
                'identification' => [
                    'identification_type' => 'KTP',
                    'identification_number' => '5171072207950001',
                    'responsible_institution' => 'Dukcapil Denpasar',
                    'country' => 'Indonesia',
                    'region' => 'Bali',
                    'valid_from' => '2013-07-22',
                    'valid_to' => '2033-07-22',
                    'entry_date' => '2013-07-22',
                ],
                'family' => [
                    'name' => 'Made Prasetya',
                    'title' => 'Mr.',
                    'relation' => 'Parent',
                    'gender' => 'Laki-laki',
                    'religion' => 'Hindu',
                    'country' => 'Indonesia',
                    'birth_place' => 'Denpasar',
                    'birth_date' => '1968-04-10',
                    'occupation' => 'Entrepreneur',
                    'is_alive' => true,
                    'valid_from' => '1995-07-22',
                ],
                'education' => [
                    'education_type' => 'S1',
                    'institute_place' => 'Universitas Udayana',
                    'country' => 'Indonesia',
                    'degree' => 'Sarjana Komputer',
                    'duration_of_course' => '4 years',
                    'final_grade' => '3.45',
                    'branch_of_study' => 'Sistem Informasi',
                    'start_year' => 2013,
                    'graduation_year' => 2017,
                    'unit' => 'Fakultas Teknik',
                    'valid_from' => '2017-09-01',
                    'attachment_name' => 'Ijazah S1',
                ],
                'qualification' => [
                    'qualification_type' => 'Certification',
                    'module' => 'Laravel Developer',
                    'language' => 'English',
                    'qualification_level' => 'Intermediate',
                    'first_year' => '2021',
                    'certified' => true,
                    'dpm' => false,
                    'dsm' => true,
                    'valid_to' => '2026-06-30',
                    'valid_from' => '2021-06-30',
                ],
                'contract' => [
                    'contract_number' => 'CONT-2022-002-EXT',
                    'contract_name' => 'External Contract',
                    'contract_type' => 'PKWT',
                    'contract_date' => '2022-03-10',
                    'position' => 'External Consultant',
                    'salary' => 8000000.00,
                    'start_date' => '2022-03-15',
                    'end_date' => '2025-03-14',
                    'is_active' => true,
                ],
                'bank' => [
                    'bank_name' => 'Bank BCA',
                    'bank_key' => 'BCA',
                    'account_number' => '5430023456789',
                    'account_holder' => 'Arogya Prasetya',
                    'valid_from' => '2022-03-15',
                ],
                'payment' => [
                    'amount' => 8000000.00,
                    'paid_at' => '2024-10-01',
                    'payment_method' => 'Transfer',
                    'reference_number' => 'PAY-2024-10-002',
                    'payment_status' => 'Completed',
                ],
            ],

            // 4. DARA
            [
                'eci' => 'ECI003',
                'basic' => [
                    'title' => 'Ms.',
                    'nick_name' => 'Dara',
                    'gender' => 'Perempuan',
                    'religion' => 'Islam',
                    'first_name' => 'Dara',
                    'last_name' => 'Safitri',
                    'search_term_1' => 'DARA',
                    'search_term_2' => 'SAFITRI',
                    'marital_status' => 'Belum Menikah',
                    'birth_date' => '1997-09-10',
                    'birth_place' => 'Yogyakarta',
                    'since_date' => '2021-06-01',
                    'created_by' => 'HR Admin',
                    'created_on' => Carbon::now(),
                    'personnel_area' => 'PA-YOG',
                    'personnel_subarea' => 'PSA-SLEMAN',
                    'employee_group' => 'Professional',
                    'employee_subgroup' => 'Consultant',
                    'position' => 'Consultant',
                    'division' => 'Consulting Services',
                    'department' => 'Business Consulting',
                    'direct_supervision' => 'ECI001',
                    'manager' => 'Ari Wibowo',
                    'authorization_group' => 'ANALYST',
                    'block' => false,
                    'deletion_flag' => false,
                ],
                'address' => [
                    'address_type' => 'Home',
                    'country' => 'Indonesia',
                    'region' => 'DI Yogyakarta',
                    'city' => 'Yogyakarta',
                    'district' => 'Sleman',
                    'rural_urban_village' => 'Maguwo',
                    'street' => 'Jl. Ring Road Utara',
                    'house_number' => '88',
                    'postal_code' => '55282',
                    'language' => 'Indonesian',
                    'cell_phone_country' => 'ID',
                    'telephone_country' => 'ID',
                    'preferred_communication' => 'email',
                    'cell_phone' => '081234567003',
                    'telephone' => '0274-512347',
                    'email_personal' => 'dara.safitri@gmail.com',
                    'email_work' => 'dara@eclectic.co.id',
                    'valid_from' => '2021-06-01',
                    'is_primary' => true,
                    'is_verified' => true,
                ],
                'identification' => [
                    'identification_type' => 'KTP',
                    'identification_number' => '3404015009970001',
                    'responsible_institution' => 'Dukcapil Sleman',
                    'country' => 'Indonesia',
                    'region' => 'DI Yogyakarta',
                    'valid_from' => '2015-09-10',
                    'valid_to' => '2035-09-10',
                    'entry_date' => '2015-09-10',
                ],
                'family' => [
                    'name' => 'Budi Safitri',
                    'title' => 'Mr.',
                    'relation' => 'Parent',
                    'gender' => 'Laki-laki',
                    'religion' => 'Islam',
                    'country' => 'Indonesia',
                    'birth_place' => 'Yogyakarta',
                    'birth_date' => '1970-02-15',
                    'occupation' => 'Teacher',
                    'is_alive' => true,
                    'valid_from' => '1997-09-10',
                ],
                'education' => [
                    'education_type' => 'S1',
                    'institute_place' => 'UPN Veteran Yogyakarta',
                    'country' => 'Indonesia',
                    'degree' => 'Sarjana Ekonomi',
                    'duration_of_course' => '4 years',
                    'final_grade' => '3.70',
                    'branch_of_study' => 'Manajemen Bisnis',
                    'start_year' => 2015,
                    'graduation_year' => 2019,
                    'unit' => 'Fakultas Ekonomi',
                    'valid_from' => '2019-09-01',
                    'attachment_name' => 'Ijazah S1',
                ],
                'qualification' => [
                    'qualification_type' => 'Certification',
                    'module' => 'Business Analysis Professional',
                    'language' => 'English',
                    'qualification_level' => 'Professional',
                    'first_year' => '2022',
                    'certified' => true,
                    'dpm' => false,
                    'dsm' => true,
                    'valid_to' => '2027-04-15',
                    'valid_from' => '2022-04-15',
                ],
                'contract' => [
                    'contract_number' => 'CONT-2021-003',
                    'contract_name' => 'Permanent Employment',
                    'contract_type' => 'PKWTT',
                    'contract_date' => '2021-05-25',
                    'position' => 'Business Analyst',
                    'salary' => 9000000.00,
                    'start_date' => '2021-06-01',
                    'is_active' => true,
                ],
                'bank' => [
                    'bank_name' => 'Bank BNI',
                    'bank_key' => 'BNINIDJA',
                    'account_number' => '0123456789012',
                    'account_holder' => 'Dara Safitri',
                    'valid_from' => '2021-06-01',
                ],
                'payment' => [
                    'amount' => 9000000.00,
                    'paid_at' => '2024-10-01',
                    'payment_method' => 'Transfer',
                    'reference_number' => 'PAY-2024-10-003',
                    'payment_status' => 'Completed',
                ],
            ],

            // 5. GILFAN
            [
                'eci' => 'ECI004',
                'basic' => [
                    'title' => 'Mr.',
                    'nick_name' => 'Gilfan',
                    'gender' => 'Laki-laki',
                    'religion' => 'Islam',
                    'first_name' => 'Gilfan',
                    'last_name' => 'Akbar',
                    'search_term_1' => 'GILFAN',
                    'search_term_2' => 'AKBAR',
                    'marital_status' => 'Belum Menikah',
                    'birth_date' => '1996-11-05',
                    'birth_place' => 'Semarang',
                    'since_date' => '2021-08-01',
                    'created_by' => 'HR Admin',
                    'created_on' => Carbon::now(),
                    'personnel_area' => 'PA-YOG',
                    'personnel_subarea' => 'PSA-SLEMAN',
                    'employee_group' => 'Professional',
                    'employee_subgroup' => 'Consultant',
                    'position' => 'Consultant',
                    'division' => 'Consulting Services',
                    'department' => 'Project Delivery',
                    'direct_supervision' => 'ECI001',
                    'manager' => 'Ari Wibowo',
                    'authorization_group' => 'DEVELOPER',
                    'block' => false,
                    'deletion_flag' => false,
                ],
                'address' => [
                    'address_type' => 'Home',
                    'country' => 'Indonesia',
                    'region' => 'DI Yogyakarta',
                    'city' => 'Yogyakarta',
                    'district' => 'Sleman',
                    'rural_urban_village' => 'Karang Malang',
                    'street' => 'Jl. C Simanjuntak',
                    'house_number' => '22',
                    'postal_code' => '55281',
                    'language' => 'Indonesian',
                    'cell_phone_country' => 'ID',
                    'telephone_country' => 'ID',
                    'preferred_communication' => 'phone',
                    'cell_phone' => '081234567004',
                    'telephone' => '0274-512348',
                    'email_personal' => 'gilfan.akbar@gmail.com',
                    'email_work' => 'gilfan@eclectic.co.id',
                    'valid_from' => '2021-08-01',
                    'is_primary' => true,
                    'is_verified' => true,
                ],
                'identification' => [
                    'identification_type' => 'KTP',
                    'identification_number' => '3374050511960001',
                    'responsible_institution' => 'Dukcapil Semarang',
                    'country' => 'Indonesia',
                    'region' => 'Jawa Tengah',
                    'valid_from' => '2014-11-05',
                    'valid_to' => '2034-11-05',
                    'entry_date' => '2014-11-05',
                ],
                'family' => [
                    'name' => 'Ahmad Akbar',
                    'title' => 'Mr.',
                    'relation' => 'Parent',
                    'gender' => 'Laki-laki',
                    'religion' => 'Islam',
                    'country' => 'Indonesia',
                    'birth_place' => 'Semarang',
                    'birth_date' => '1969-08-12',
                    'occupation' => 'Engineer',
                    'is_alive' => true,
                    'valid_from' => '1996-11-05',
                ],
                'education' => [
                    'education_type' => 'S1',
                    'institute_place' => 'Universitas Dian Nuswantoro',
                    'country' => 'Indonesia',
                    'degree' => 'Sarjana Komputer',
                    'duration_of_course' => '4 years',
                    'final_grade' => '3.55',
                    'branch_of_study' => 'Teknik Informatika',
                    'start_year' => 2014,
                    'graduation_year' => 2018,
                    'unit' => 'Fakultas Ilmu Komputer',
                    'valid_from' => '2018-09-01',
                    'attachment_name' => 'Ijazah S1',
                ],
                'qualification' => [
                    'qualification_type' => 'Certification',
                    'module' => 'Full Stack Developer',
                    'language' => 'English',
                    'qualification_level' => 'Intermediate',
                    'first_year' => '2020',
                    'certified' => true,
                    'dpm' => false,
                    'dsm' => true,
                    'valid_to' => '2026-08-20',
                    'valid_from' => '2020-08-20',
                ],
                'contract' => [
                    'contract_number' => 'CONT-2021-004',
                    'contract_name' => 'Permanent Employment',
                    'contract_type' => 'PKWTT',
                    'contract_date' => '2021-07-25',
                    'position' => 'Software Developer',
                    'salary' => 10000000.00,
                    'start_date' => '2021-08-01',
                    'is_active' => true,
                ],
                'bank' => [
                    'bank_name' => 'Bank Mandiri',
                    'bank_key' => 'BMRI',
                    'account_number' => '1370002345678',
                    'account_holder' => 'Gilfan Akbar',
                    'valid_from' => '2021-08-01',
                ],
                'payment' => [
                    'amount' => 10000000.00,
                    'paid_at' => '2024-10-01',
                    'payment_method' => 'Transfer',
                    'reference_number' => 'PAY-2024-10-004',
                    'payment_status' => 'Completed',
                ],
            ],

            // 6. PUTRI
            [
                'eci' => 'ECI005',
                'basic' => [
                    'title' => 'Ms.',
                    'nick_name' => 'Putri',
                    'gender' => 'Perempuan',
                    'religion' => 'Islam',
                    'first_name' => 'Putri',
                    'last_name' => 'Rahayu',
                    'search_term_1' => 'PUTRI',
                    'search_term_2' => 'RAHAYU',
                    'marital_status' => 'Belum Menikah',
                    'birth_date' => '1998-04-18',
                    'birth_place' => 'Yogyakarta',
                    'since_date' => '2022-01-10',
                    'created_by' => 'HR Admin',
                    'created_on' => Carbon::now(),
                    'personnel_area' => 'PA-YOG',
                    'personnel_subarea' => 'PSA-SLEMAN',
                    'employee_group' => 'Professional',
                    'employee_subgroup' => 'HR & Admin',
                    'position' => 'HR Coordinator',
                    'division' => 'Corporate Services',
                    'department' => 'Human Resources',
                    'direct_supervision' => 'ECI001',
                    'manager' => 'Ari Wibowo',
                    'authorization_group' => 'HR-STAFF',
                    'block' => false,
                    'deletion_flag' => false,
                ],
                'address' => [
                    'address_type' => 'Home',
                    'country' => 'Indonesia',
                    'region' => 'DI Yogyakarta',
                    'city' => 'Yogyakarta',
                    'district' => 'Sleman',
                    'rural_urban_village' => 'Sleman',
                    'street' => 'Jl. Magelang',
                    'house_number' => '15',
                    'postal_code' => '55284',
                    'language' => 'Indonesian',
                    'cell_phone_country' => 'ID',
                    'telephone_country' => 'ID',
                    'preferred_communication' => 'email',
                    'cell_phone' => '081234567005',
                    'telephone' => '0274-512349',
                    'email_personal' => 'putri.rahayu@gmail.com',
                    'email_work' => 'putri@eclectic.co.id',
                    'valid_from' => '2022-01-10',
                    'is_primary' => true,
                    'is_verified' => true,
                ],
                'identification' => [
                    'identification_type' => 'KTP',
                    'identification_number' => '3404015804980001',
                    'responsible_institution' => 'Dukcapil Sleman',
                    'country' => 'Indonesia',
                    'region' => 'DI Yogyakarta',
                    'valid_from' => '2016-04-18',
                    'valid_to' => '2036-04-18',
                    'entry_date' => '2016-04-18',
                ],
                'family' => [
                    'name' => 'Sri Rahayu',
                    'title' => 'Mrs.',
                    'relation' => 'Parent',
                    'gender' => 'Perempuan',
                    'religion' => 'Islam',
                    'country' => 'Indonesia',
                    'birth_place' => 'Yogyakarta',
                    'birth_date' => '1972-11-20',
                    'occupation' => 'Housewife',
                    'is_alive' => true,
                    'valid_from' => '1998-04-18',
                ],
                'education' => [
                    'education_type' => 'S1',
                    'institute_place' => 'Universitas Ahmad Dahlan',
                    'country' => 'Indonesia',
                    'degree' => 'Sarjana Psikologi',
                    'duration_of_course' => '4 years',
                    'final_grade' => '3.60',
                    'branch_of_study' => 'Psikologi',
                    'start_year' => 2016,
                    'graduation_year' => 2020,
                    'unit' => 'Fakultas Psikologi',
                    'valid_from' => '2020-09-01',
                    'attachment_name' => 'Ijazah S1',
                ],
                'qualification' => [
                    'qualification_type' => 'Certification',
                    'module' => 'Human Resources Management',
                    'language' => 'Indonesian',
                    'qualification_level' => 'Intermediate',
                    'first_year' => '2021',
                    'certified' => true,
                    'dpm' => false,
                    'dsm' => false,
                    'valid_to' => '2026-12-31',
                    'valid_from' => '2021-06-15',
                ],
                'contract' => [
                    'contract_number' => 'CONT-2022-005',
                    'contract_name' => 'Permanent Employment',
                    'contract_type' => 'PKWTT',
                    'contract_date' => '2022-01-05',
                    'position' => 'HR Coordinator',
                    'salary' => 7500000.00,
                    'start_date' => '2022-01-10',
                    'is_active' => true,
                ],
                'bank' => [
                    'bank_name' => 'Bank BCA',
                    'bank_key' => 'BCA',
                    'account_number' => '5430034567890',
                    'account_holder' => 'Putri Rahayu',
                    'valid_from' => '2022-01-10',
                ],
                'payment' => [
                    'amount' => 7500000.00,
                    'paid_at' => '2024-10-01',
                    'payment_method' => 'Transfer',
                    'reference_number' => 'PAY-2024-10-005',
                    'payment_status' => 'Completed',
                ],
            ],

            // Continue dengan employee lainnya...
            // Saya akan membuat template untuk nama-nama berikutnya

        ];

        // Tambahan employee dengan format yang sama
        // employee_subgroup: Consultant, Sales, HR & Admin, Finance, Admin Delivery, Admin Support
        // position: Senior Consultant, Consultant, Junior Consultant, Sales, HR Staff, Admin Staff, Finance Staff, Finance Manager, Admin Delivery, Admin Support, Project Manager
        $additionalEmployees = [
            ['eci' => 'ECI006', 'first_name' => 'Agus', 'last_name' => 'Fahyadi', 'nick_name' => 'Agus Fahyadi', 'employee_subgroup' => 'Consultant', 'position' => 'Consultant'],
            ['eci' => 'ECI007', 'first_name' => 'Raditya', 'last_name' => 'Budi Handoko', 'nick_name' => 'Raditya', 'employee_subgroup' => 'Consultant', 'position' => 'Junior Consultant'],
            ['eci' => 'ECI008', 'first_name' => 'Galih', 'last_name' => 'Pratama', 'nick_name' => 'Galih', 'employee_subgroup' => 'Consultant', 'position' => 'Consultant'],
            ['eci' => 'ECI009', 'first_name' => 'Fawwaz', 'last_name' => 'Rahman', 'nick_name' => 'Fawwaz', 'employee_subgroup' => 'Consultant', 'position' => 'Consultant'],
            ['eci' => 'ECI010', 'first_name' => 'Said', 'last_name' => 'Abdullah', 'nick_name' => 'Said', 'employee_subgroup' => 'Consultant', 'position' => 'Senior Consultant'],
            ['eci' => 'ECI011', 'first_name' => 'Excel', 'last_name' => 'Wijaya', 'nick_name' => 'Excel', 'employee_subgroup' => 'Consultant', 'position' => 'Consultant'],
            ['eci' => 'ECI012', 'first_name' => 'Agus', 'last_name' => 'Dwi Santoso', 'nick_name' => 'Agus Dwi', 'employee_subgroup' => 'Consultant', 'position' => 'Senior Consultant'],
            ['eci' => 'ECI013', 'first_name' => 'Alif', 'last_name' => 'Hidayat', 'nick_name' => 'Alif', 'employee_subgroup' => 'Consultant', 'position' => 'Junior Consultant'],
            ['eci' => 'ECI014', 'first_name' => 'Qoni', 'last_name' => 'Maulana', 'nick_name' => 'Qoni', 'employee_subgroup' => 'Consultant', 'position' => 'Consultant'],
            ['eci' => 'ECI015', 'first_name' => 'Bagas', 'last_name' => 'Prasetyo', 'nick_name' => 'Bagas', 'employee_subgroup' => 'Consultant', 'position' => 'Project Manager'],
            ['eci' => 'ECI016', 'first_name' => 'Fikri', 'last_name' => 'Ramadhan', 'nick_name' => 'Fikri', 'employee_subgroup' => 'Consultant', 'position' => 'Junior Consultant'],
            ['eci' => 'ECI017', 'first_name' => 'Gideon', 'last_name' => 'Siahaan', 'nick_name' => 'Gideon', 'employee_subgroup' => 'Consultant', 'position' => 'Consultant', 'religion' => 'Kristen'],
            ['eci' => 'ECI018', 'first_name' => 'Resita', 'last_name' => 'Anggraini', 'nick_name' => 'Resita', 'employee_subgroup' => 'Admin Delivery', 'position' => 'Admin Delivery', 'gender' => 'Perempuan'],
            ['eci' => 'ECI019', 'first_name' => 'Putri', 'last_name' => 'Nurfita', 'nick_name' => 'Putrinurfita', 'employee_subgroup' => 'HR & Admin', 'position' => 'Admin Staff', 'gender' => 'Perempuan'],
            ['eci' => 'ECI020', 'first_name' => 'Gian', 'last_name' => 'Ramadhan', 'nick_name' => 'Gian', 'employee_subgroup' => 'Consultant', 'position' => 'Consultant'],
            ['eci' => 'ECI021', 'first_name' => 'Meitarisha', 'last_name' => 'Dewi', 'nick_name' => 'Meitarisha', 'employee_subgroup' => 'Sales', 'position' => 'Sales', 'gender' => 'Perempuan'],
            ['eci' => 'ECI022', 'first_name' => 'Yudha', 'last_name' => 'Pratama', 'nick_name' => 'Yudha', 'employee_subgroup' => 'Consultant', 'position' => 'Consultant'],
            ['eci' => 'ECI023', 'first_name' => 'Dhira', 'last_name' => 'Ananda', 'nick_name' => 'Dhira', 'employee_subgroup' => 'Admin Support', 'position' => 'Admin Support', 'gender' => 'Perempuan'],
            ['eci' => 'ECI024', 'first_name' => 'Farah', 'last_name' => 'Nabila', 'nick_name' => 'Farah', 'employee_subgroup' => 'HR & Admin', 'position' => 'HR Staff', 'gender' => 'Perempuan'],
            ['eci' => 'ECI025', 'first_name' => 'Vira', 'last_name' => 'Safitri', 'nick_name' => 'Vira', 'employee_subgroup' => 'Sales', 'position' => 'Sales', 'gender' => 'Perempuan'],
            ['eci' => 'ECI026', 'first_name' => 'Wahyu', 'last_name' => 'Setiawan', 'nick_name' => 'Wahyu', 'employee_subgroup' => 'Consultant', 'position' => 'Junior Consultant'],
            ['eci' => 'ECI027', 'first_name' => 'Kahfi', 'last_name' => 'Maulana', 'nick_name' => 'Kahfi', 'employee_subgroup' => 'Consultant', 'position' => 'Junior Consultant'],
            ['eci' => 'ECI028', 'first_name' => 'Salma', 'last_name' => 'Azzahra', 'nick_name' => 'Salma', 'employee_subgroup' => 'Admin Delivery', 'position' => 'Admin Delivery', 'gender' => 'Perempuan'],
            ['eci' => 'ECI029', 'first_name' => 'Loisa', 'last_name' => 'Margaretha', 'nick_name' => 'Loisa', 'employee_subgroup' => 'Finance', 'position' => 'Finance Staff', 'gender' => 'Perempuan', 'religion' => 'Kristen'],
            ['eci' => 'ECI030', 'first_name' => 'Meliza', 'last_name' => 'Putri', 'nick_name' => 'Meliza', 'employee_subgroup' => 'HR & Admin', 'position' => 'HR Staff', 'gender' => 'Perempuan'],
            ['eci' => 'ECI031', 'first_name' => 'Galih', 'last_name' => 'Saputra', 'nick_name' => 'Galih', 'employee_subgroup' => 'Consultant', 'position' => 'Consultant'],
            ['eci' => 'ECI032', 'first_name' => 'Devi', 'last_name' => 'Anggraeni', 'nick_name' => 'Devi', 'employee_subgroup' => 'Admin Support', 'position' => 'Admin Support', 'gender' => 'Perempuan'],
            ['eci' => 'ECI033', 'first_name' => 'Ega', 'last_name' => 'Ramadhan', 'nick_name' => 'Ega', 'employee_subgroup' => 'Consultant', 'position' => 'Consultant'],
            ['eci' => 'ECI034', 'first_name' => 'Luluk', 'last_name' => 'Rohmawati', 'nick_name' => 'Luluk', 'employee_subgroup' => 'Finance', 'position' => 'Finance Staff', 'gender' => 'Perempuan'],
            ['eci' => 'ECI035', 'first_name' => 'Erwin', 'last_name' => 'Setiawan', 'nick_name' => 'Erwin', 'employee_subgroup' => 'Consultant', 'position' => 'Senior Consultant'],
            ['eci' => 'ECI036', 'first_name' => 'Alif', 'last_name' => 'Faturahman', 'nick_name' => 'Alif', 'employee_subgroup' => 'Consultant', 'position' => 'Junior Consultant'],
            ['eci' => 'ECI037', 'first_name' => 'Bramila', 'last_name' => 'Sari', 'nick_name' => 'Bramila', 'employee_subgroup' => 'Sales', 'position' => 'Sales', 'gender' => 'Perempuan'],
            ['eci' => 'ECI038', 'first_name' => 'Miftah', 'last_name' => 'Farid', 'nick_name' => 'Miftah', 'employee_subgroup' => 'Consultant', 'position' => 'Project Manager'],
            ['eci' => 'ECI039', 'first_name' => 'Ela', 'last_name' => 'Amalia', 'nick_name' => 'Ela Amalia', 'employee_subgroup' => 'HR & Admin', 'position' => 'Admin Staff', 'gender' => 'Perempuan'],
            ['eci' => 'ECI040', 'first_name' => 'Tjendra', 'last_name' => 'Wijaya', 'nick_name' => 'Tjendra', 'employee_subgroup' => 'Finance', 'position' => 'Finance Manager', 'religion' => 'Buddha'],
            ['eci' => 'ECI041', 'first_name' => 'Usman', 'last_name' => 'Hakim', 'nick_name' => 'Usman', 'employee_subgroup' => 'Consultant', 'position' => 'Senior Consultant'],
            ['eci' => 'ECI042', 'first_name' => 'Budi', 'last_name' => 'Santoso', 'nick_name' => 'Budi', 'employee_subgroup' => 'Consultant', 'position' => 'Consultant'],
            ['eci' => 'ECI043', 'first_name' => 'Kifni', 'last_name' => 'Kurniawan', 'nick_name' => 'Kifni Kurniawan', 'employee_subgroup' => 'Consultant', 'position' => 'Consultant'],
            ['eci' => 'ECI044', 'first_name' => 'Hardika', 'last_name' => 'Pratama', 'nick_name' => 'Hardika', 'employee_subgroup' => 'Consultant', 'position' => 'Project Manager'],
            ['eci' => 'ECI045', 'first_name' => 'Christian', 'last_name' => 'Budiman', 'nick_name' => 'Christian', 'employee_subgroup' => 'Consultant', 'position' => 'Senior Consultant', 'religion' => 'Kristen'],
            ['eci' => 'ECI046', 'first_name' => 'Akbar', 'last_name' => 'Maulana', 'nick_name' => 'Akbar', 'employee_subgroup' => 'Admin Delivery', 'position' => 'Admin Delivery'],
            ['eci' => 'ECI047', 'first_name' => 'Dony', 'last_name' => 'Setiawan', 'nick_name' => 'Dony', 'employee_subgroup' => 'Consultant', 'position' => 'Consultant'],
            ['eci' => 'ECI048', 'first_name' => 'Adi', 'last_name' => 'Nugroho', 'nick_name' => 'Adi Nugroho', 'employee_subgroup' => 'Consultant', 'position' => 'Senior Consultant'],
            ['eci' => 'ECI049', 'first_name' => 'Miftah', 'last_name' => 'Fauzan', 'nick_name' => 'Miftah', 'employee_subgroup' => 'Consultant', 'position' => 'Consultant'],
            ['eci' => 'ECI050', 'first_name' => 'Aaliya', 'last_name' => 'Azzahra', 'nick_name' => 'Aaliya', 'employee_subgroup' => 'Admin Support', 'position' => 'Admin Support', 'gender' => 'Perempuan'],
            ['eci' => 'ECI051', 'first_name' => 'Tami', 'last_name' => 'Wulandari', 'nick_name' => 'Tami', 'employee_subgroup' => 'Sales', 'position' => 'Sales', 'gender' => 'Perempuan'],
            ['eci' => 'ECI052', 'first_name' => 'Rofiq', 'last_name' => 'Abdillah', 'nick_name' => 'Rofiq', 'employee_subgroup' => 'Consultant', 'position' => 'Consultant'],
        ];

        // Generate data lengkap untuk additional employees
        foreach ($additionalEmployees as $index => $addEmp) {
            $baseYear = 1990 + ($index % 10);
            $baseMonth = 1 + ($index % 12);
            $baseDay = 1 + ($index % 28);
            $gender = $addEmp['gender'] ?? 'Laki-laki';
            $religion = $addEmp['religion'] ?? 'Islam';
            // Removed is_external flag as Contractor position no longer exists
            
            $employee = [
                'eci' => $addEmp['eci'],
                'basic' => [
                    'title' => $gender === 'Perempuan' ? 'Ms.' : 'Mr.',
                    'nick_name' => $addEmp['nick_name'],
                    'gender' => $gender,
                    'religion' => $religion,
                    'first_name' => $addEmp['first_name'],
                    'last_name' => $addEmp['last_name'],
                    'search_term_1' => strtoupper($addEmp['first_name']),
                    'search_term_2' => strtoupper($addEmp['last_name']),
                    'marital_status' => $index % 3 === 0 ? 'Menikah' : 'Belum Menikah',
                    'birth_date' => sprintf('%04d-%02d-%02d', $baseYear, $baseMonth, $baseDay),
                    'birth_place' => ['Yogyakarta', 'Semarang', 'Jakarta', 'Surabaya', 'Bandung'][$index % 5],
                    'since_date' => Carbon::now()->subYears(2 + ($index % 5))->format('Y-m-d'),
                    'created_by' => 'HR Admin',
                    'created_on' => Carbon::now(),
                    'personnel_area' => 'PA-YOG',
                    'personnel_subarea' => 'PSA-SLEMAN',
                    'employee_group' => 'Professional',
                    'employee_subgroup' => $addEmp['employee_subgroup'],
                    'position' => $addEmp['position'],
                    'division' => in_array($addEmp['employee_subgroup'], ['Consultant', 'Admin Delivery', 'Admin Support']) ? 'Consulting Services' : (in_array($addEmp['employee_subgroup'], ['Sales']) ? 'Sales' : 'Corporate Services'),
                    'department' => $addEmp['employee_subgroup'] === 'Consultant' ? 'Business Consulting' : $addEmp['employee_subgroup'],
                    'direct_supervision' => 'ECI001',
                    'manager' => 'Ari Wibowo',
                    'authorization_group' => 'STAFF',
                    'block' => false,
                    'deletion_flag' => false,
                ],
                'address' => [
                    'address_type' => 'Home',
                    'country' => 'Indonesia',
                    'region' => 'DI Yogyakarta',
                    'city' => 'Yogyakarta',
                    'district' => 'Sleman',
                    'rural_urban_village' => ['Condong Catur', 'Catur Tunggal', 'Depok', 'Maguwo', 'Sleman'][$index % 5],
                    'street' => 'Jl. ' . ['Kaliurang', 'Affandi', 'Seturan', 'Ring Road', 'Magelang'][$index % 5],
                    'house_number' => strval(10 + $index),
                    'postal_code' => '55281',
                    'language' => 'Indonesian',
                    'cell_phone_country' => 'ID',
                    'telephone_country' => 'ID',
                    'preferred_communication' => 'email',
                    'cell_phone' => sprintf('08123456%04d', 7000 + $index),
                    'telephone' => sprintf('0274-51%04d', 2350 + $index),
                    'email_personal' => strtolower($addEmp['first_name'] . '.' . $addEmp['last_name']) . '@gmail.com',
                    'email_work' => strtolower($addEmp['first_name']) . '@eclectic.co.id',
                    'valid_from' => Carbon::now()->subYears(2 + ($index % 5))->format('Y-m-d'),
                    'is_primary' => true,
                    'is_verified' => true,
                ],
                'identification' => [
                    'identification_type' => 'KTP',
                    'identification_number' => sprintf('34040%02d%02d%02d%04d', $baseDay, $baseMonth, $baseYear - 1900, $index + 100),
                    'responsible_institution' => 'Dukcapil Sleman',
                    'country' => 'Indonesia',
                    'region' => 'DI Yogyakarta',
                    'valid_from' => sprintf('%04d-%02d-%02d', $baseYear + 18, $baseMonth, $baseDay),
                    'valid_to' => sprintf('%04d-%02d-%02d', $baseYear + 38, $baseMonth, $baseDay),
                    'entry_date' => sprintf('%04d-%02d-%02d', $baseYear + 18, $baseMonth, $baseDay),
                ],
                'family' => [
                    'name' => $gender === 'Perempuan' ? 'Ibu ' . $addEmp['last_name'] : 'Bapak ' . $addEmp['last_name'],
                    'title' => $gender === 'Perempuan' ? 'Mrs.' : 'Mr.',
                    'relation' => 'Parent',
                    'gender' => 'Laki-laki',
                    'religion' => $religion,
                    'country' => 'Indonesia',
                    'birth_place' => 'Yogyakarta',
                    'birth_date' => sprintf('%04d-%02d-%02d', $baseYear - 30, $baseMonth, $baseDay),
                    'occupation' => ['Teacher', 'Engineer', 'Entrepreneur', 'Civil Servant', 'Doctor'][$index % 5],
                    'is_alive' => true,
                    'valid_from' => sprintf('%04d-%02d-%02d', $baseYear, $baseMonth, $baseDay),
                ],
                'education' => [
                    'education_type' => 'S1',
                    'institute_place' => ['Universitas Gadjah Mada', 'UPN Veteran Yogyakarta', 'Universitas Atma Jaya', 'Universitas Ahmad Dahlan', 'Universitas Sanata Dharma'][$index % 5],
                    'country' => 'Indonesia',
                    'degree' => strpos($addEmp['position'], 'Developer') !== false || strpos($addEmp['position'], 'IT') !== false ? 'Sarjana Komputer' : (strpos($addEmp['position'], 'Finance') !== false ? 'Sarjana Ekonomi' : 'Sarjana'),
                    'duration_of_course' => '4 years',
                    'final_grade' => sprintf('3.%02d', 45 + ($index % 40)),
                    'branch_of_study' => strpos($addEmp['position'], 'Developer') !== false ? 'Teknik Informatika' : (strpos($addEmp['position'], 'Finance') !== false ? 'Akuntansi' : 'Manajemen'),
                    'start_year' => $baseYear + 18,
                    'graduation_year' => $baseYear + 22,
                    'unit' => 'Fakultas ' . (strpos($addEmp['position'], 'Developer') !== false ? 'Teknik' : 'Ekonomi'),
                    'valid_from' => sprintf('%04d-09-01', $baseYear + 22),
                    'attachment_name' => 'Ijazah S1',
                ],
                'qualification' => [
                    'qualification_type' => 'Certification',
                    'module' => strpos($addEmp['position'], 'Developer') !== false ? 'Professional Developer' : (strpos($addEmp['position'], 'Consultant') !== false ? 'Business Consulting' : 'Professional Certificate'),
                    'language' => 'English',
                    'qualification_level' => ['Intermediate', 'Professional', 'Expert'][$index % 3],
                    'first_year' => strval($baseYear + 24),
                    'certified' => true,
                    'dpm' => $index % 2 === 0,
                    'dsm' => $index % 2 === 1,
                    'valid_to' => sprintf('%04d-12-31', $baseYear + 30),
                    'valid_from' => sprintf('%04d-06-15', $baseYear + 24),
                ],
                'contract' => [
                    'contract_number' => sprintf('CONT-%s-%03d', date('Y'), $index + 6),
                    'contract_name' => 'Permanent Employment',
                    'contract_type' => 'PKWTT',
                    'contract_date' => Carbon::now()->subYears(2 + ($index % 5))->subDays(5)->format('Y-m-d'),
                    'position' => $addEmp['position'],
                    'salary' => (6000000 + ($index * 250000)),
                    'start_date' => Carbon::now()->subYears(2 + ($index % 5))->format('Y-m-d'),
                    'end_date' => null,
                    'is_active' => true,
                ],
                'bank' => [
                    'bank_name' => ['Bank BCA', 'Bank Mandiri', 'Bank BNI', 'Bank BRI'][$index % 4],
                    'bank_key' => ['BCA', 'BMRI', 'BNINIDJA', 'BRINIDJA'][$index % 4],
                    'account_number' => sprintf('%013d', 5430000000000 + $index * 1000000),
                    'account_holder' => $addEmp['first_name'] . ' ' . $addEmp['last_name'],
                    'valid_from' => Carbon::now()->subYears(2 + ($index % 5))->format('Y-m-d'),
                ],
                'payment' => [
                    'amount' => (6000000 + ($index * 250000)),
                    'paid_at' => '2024-10-01',
                    'payment_method' => 'Transfer',
                    'reference_number' => sprintf('PAY-2024-10-%03d', $index + 6),
                    'payment_status' => 'Completed',
                ],
            ];
            
            $employees[] = $employee;
        }

        // Proses seeding
        foreach ($employees as $emp) {
            DB::beginTransaction();
            try {
                // Check if employee already exists
                $existingEmployee = DB::table('employee')->where('eci', $emp['eci'])->first();

                if ($existingEmployee) {
                    DB::rollBack();
                    $this->command->info("⊙ Employee {$emp['eci']} sudah ada, skipped");
                    continue;
                }

                // 1. BUAT EMPLOYEE TERLEBIH DAHULU
                $employeeId = DB::table('employee')->insertGetId([
                    'role_id' => $emp['role_id'] ?? 2,
                    'eci' => $emp['eci'],
                    'is_active' => true,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ]);

                // 2-10. Insert semua data terkait
                DB::table('employee_basic_data')->insert(array_merge($emp['basic'], [
                    'employee_id' => $employeeId,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ]));

                DB::table('employee_address')->insert(array_merge($emp['address'], [
                    'employee_id' => $employeeId,
                    'fax_country' => null,
                    'telephone_extension' => null,
                    'fax' => null,
                    'fax_extension' => null,
                    'website' => null,
                    'valid_to' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ]));

                DB::table('employee_identification')->insert(array_merge($emp['identification'], [
                    'employee_id' => $employeeId,
                    'drive_link' => null,
                    'verify_link' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ]));

                DB::table('employee_family')->insert(array_merge($emp['family'], [
                    'employee_id' => $employeeId,
                    'valid_to' => null,
                    'verify_link' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ]));

                DB::table('employee_education')->insert(array_merge($emp['education'], [
                    'employee_id' => $employeeId,
                    'valid_to' => null,
                    'attachment_verify_link' => null,
                    'attachment_drive_link' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ]));

                DB::table('employee_qualification')->insert(array_merge($emp['qualification'], [
                    'employee_id' => $employeeId,
                    'drive_link' => null,
                    'verify_link' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ]));

                DB::table('employee_contract')->insert(array_merge($emp['contract'], [
                    'employee_id' => $employeeId,
                    'end_date' => $emp['contract']['end_date'] ?? null,
                    'drive_link' => null,
                    'verify_link' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ]));

                DB::table('employee_bank')->insert(array_merge($emp['bank'], [
                    'employee_id' => $employeeId,
                    'drive_link' => null,
                    'valid_to' => null,
                    'verify_link' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ]));

                DB::table('employee_payment')->insert(array_merge($emp['payment'], [
                    'employee_id' => $employeeId,
                    'valid_to' => null,
                    'drive_link' => null,
                    'verify_link' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ]));

                DB::table('employee_attachment')->insert([
                    'employee_id' => $employeeId,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ]);

                // BUAT AUTH_USER untuk employee
                // Login bisa menggunakan: ECI (username), email_work (email), atau nick_name
                $authEmail = $emp['address']['email_work'];
                $authPhone = $emp['address']['cell_phone'];

                // Cek apakah auth_user sudah ada (email atau username duplikat)
                $authExists = DB::table('auth_users')
                    ->where('email', $authEmail)
                    ->orWhere('username', $emp['eci'])
                    ->exists();

                if (!$authExists) {
                    DB::table('auth_users')->insert([
                        'employee_id' => $employeeId,
                        'customer_id' => null,
                        'username'    => $emp['eci'],
                        'email'       => $authEmail,
                        'phone'       => $authPhone,
                        'password'    => Hash::make('password123'),
                        'is_active'   => true,
                        'created_at'  => Carbon::now(),
                        'updated_at'  => Carbon::now(),
                    ]);
                }

                DB::commit();
                $this->command->info("✓ Employee {$emp['eci']} - {$emp['basic']['first_name']} {$emp['basic']['last_name']} berhasil diseed");

            } catch (\Exception $e) {
                DB::rollBack();
                $this->command->error("✗ Error untuk {$emp['eci']}: " . $e->getMessage());
            }
        }

        $this->command->info('✓ Seeding Employee Eclectic Consulting selesai! Total: ' . count($employees) . ' employees');
    }
}