<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Gantt Chart - {{ $project->name }}</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'DejaVu Sans', Arial, sans-serif;
            font-size: 8px;
            color: #1f2937;
        }
        
        .header {
            margin-bottom: 15px;
            padding: 10px;
            background: #f3f4f6;
            border-bottom: 3px solid #4f46e5;
        }
        
        .header h1 {
            font-size: 16px;
            color: #1f2937;
            margin-bottom: 5px;
        }
        
        .header-info {
            font-size: 8px;
            color: #6b7280;
        }
        
        .gantt-container {
            margin-top: 10px;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
        }
        
        th {
            background: #4f46e5;
            color: white;
            padding: 6px 4px;
            text-align: left;
            font-weight: bold;
            font-size: 7px;
            border: 1px solid #3730a3;
        }
        
        td {
            padding: 5px 3px;
            border: 1px solid #d1d5db;
            font-size: 7px;
        }
        
        .phase-row {
            background: #e0e7ff;
            font-weight: bold;
        }
        
        .group-row {
            background: #f3f4f6;
        }
        
        .stage-row {
            background: #fef3c7;
        }
        
        .timeline-cell {
            text-align: center;
            padding: 3px;
        }
        
        .gantt-bar {
            display: inline-block;
            height: 10px;
            border-radius: 2px;
        }
        
        .bar-phase { background: #6366f1; }
        .bar-group { background: #8b5cf6; }
        .bar-stage { background: #f59e0b; }
        
        .indent-1 { padding-left: 8px !important; }
        .indent-2 { padding-left: 16px !important; }
        .indent-3 { padding-left: 24px !important; }
        
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            padding: 8px;
            text-align: center;
            font-size: 7px;
            color: #6b7280;
            border-top: 1px solid #d1d5db;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>📊 Project Planning - Gantt Chart</h1>
        <div class="header-info">
            <strong>Project:</strong> {{ $project->name }} | 
            <strong>Period:</strong> {{ $ganttData['start_date'] ?? '-' }} to {{ $ganttData['end_date'] ?? '-' }} | 
            <strong>Exported:</strong> {{ $exportDate }}
        </div>
    </div>

    <div class="gantt-container">
        <table>
            <thead>
                <tr>
                    <th style="width: 25%;">Task Name</th>
                    <th style="width: 10%;">Start</th>
                    <th style="width: 10%;">End</th>
                    <th style="width: 8%;">Progress</th>
                    <th style="width: 47%;">Timeline</th>
                </tr>
            </thead>
            <tbody>
                @if(!empty($ganttData['vertical_groups']))
                    @foreach($ganttData['vertical_groups'] as $phase)
                        {{-- Phase Row --}}
                        <tr class="phase-row">
                            <td>📋 {{ strtoupper($phase['name']) }}</td>
                            <td>-</td>
                            <td>-</td>
                            <td>{{ number_format($phase['progress'], 1) }}%</td>
                            <td class="timeline-cell">
                                <div class="gantt-bar bar-phase" style="width: 100%;"></div>
                            </td>
                        </tr>

                        {{-- Groups --}}
                        @foreach($phase['tasks'] as $group)
                            @include('project-planning.exports.partials.gantt-group', ['group' => $group, 'level' => 1])
                        @endforeach
                    @endforeach
                @endif
            </tbody>
        </table>
    </div>

    <div class="footer">
        Page <span class="pagenum"></span> | Generated by Project Planning System
    </div>
</body>
</html>